diff --git a/Makefile b/Makefile
deleted file mode 100644
index bcbc7702..00000000
--- a/Makefile
+++ /dev/null
@@ -1,9 +0,0 @@
-define newline
-
-
-endef
-
-$(error Build system changed:$(newline)\
-The Makefile build has been replaced by CMake.$(newline)$(newline)\
-For build instructions see:$(newline)\
-https://github.com/ggml-org/llama.cpp/blob/master/docs/build.md$(newline)${newline})
